### ISSUE TITLE
Add support for logging with Azure's context.log

### ISSUE THREAD

**Issue by Sherex** [vtfk/node-shared-logger#29]
Support logging with an Azure function's `context.log`.

### Things to implement/consider:
- This should not replace remote logging, but use the same message as Azure adds timestamp and severity.
- Disable local logging?
- Automatically prepend `context.invocationId` to the prefix.
- Option to not add `context.invocationId` (ex. `options.azure.excludeInvocationId: false`)
- Map logLevel to `context.log[level](message)`.

### Interaction
```js
module.exports = async function (context, req) {
  logConfig({
    azure: { 
      context,
      excludeInvocationId: true // Default: false
    }
  })
  // Insert magic here..
}
```

**Comment by MatsAnd** [comment]
Please consider mapping the log levels to its corresponding context log method, so the log message shows up correctly in Application Insights.

```js
if(level === 'info') context.log.info(message)
if(level === 'warn') context.log.warn(message)
if(level === 'error') context.log.error(message)
if(level === 'verbose') context.log.verbose(message)
else context.log(message)
```

[Azure trace level methods](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#trace-levels)
